### ISSUE TITLE
Documentation on README doesn't match NPM package

### ISSUE THREAD

**Issue by SquaredStudios-MC** [discordcf/discordcf#38]
### Description

After installing this module with the install command, I tried using the example provided in the README, but it didn't work here:
`type ApplicationCommandHandler `
I get a typescript error saying: '"cloudflare-discord-bot"' has no exported member named 'ApplicationCommandHandler'. Did you mean 'createApplicationCommandHandler'?

I am using version 0.0.4

### Version

0.0.1 (latest)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvgaona** [comment]
Hi @SquaredStudios-MC, are you looking at the latest documentation or at [this one](https://github.com/discordcf/discordcf/tree/0.0.4)?

I'm working as fast as I can to provide you guys with the latest and improved API. If you want to try this one, you could define your dependency from a Github branch.

**Comment by SquaredStudios-MC** [comment]
Thanks!
