### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by LoryPelli** [discordcf/discordcf#39]
### Description

It's not updated

### Reproducibility

Go on https://www.npmjs.com/package/cloudflare-discord-bot and see, it says 7 bmonths ago also if you made a commit 10 days ago on github

### Version

0.0.1 (latest)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Inrixia** [comment]
@alvgaona should properly deprocate the old package on npm and direct users to the new one

**Comment by alvgaona** [comment]
Hi @LoryPelli, I'm working on the documentation. Soon we'll do an initial release of what we have in `main`.

**Comment by LoryPelli** [comment]
@alvgaona so how can I use the package updated? Fork the github repo?

**Comment by LoryPelli** [comment]
@Inrixia ETA for package update?

**Comment by alvgaona** [comment]
You can declare in your `package.json` dependencies, the `main` branch of this repo to use it. Until I get the release out.

**Comment by LoryPelli** [comment]
@alvgaona the package.json of this repo? Or another one?

**Comment by alvgaona** [comment]
> @alvgaona the package.json of this repo? Or another one?

That'd be the `package.json` of your project.

**Comment by LoryPelli** [comment]
> > @alvgaona the package.json of this repo? Or another one?
> 
> That'd be the `package.json` of your project.

Fast reply...good

**Comment by alvgaona** [comment]
@LoryPelli I'll leave the issue open as I still need to update the package.

**Comment by LoryPelli** [comment]
Ok, @alvgaona does I still need to download the repo for the package.json thing?

**Comment by LoryPelli** [comment]
Why visual studio isn't able to show possible commands?

**Comment by LoryPelli** [comment]
> Why visual studio isn't able to show possible autocomplete?

Like for example with discord.js if I type client. it will show something that would work with that method

**Comment by LoryPelli** [comment]
ETA 1 month, right?

**Comment by Inrixia** [comment]
Yea sadly it's on @alvgaona to publish the new package so just waiting on them @LoryPelli

**Comment by alvgaona** [comment]
I'll try to have the release on December, 20th.
