### ISSUE TITLE
Embeds

### ISSUE THREAD

**Issue by LoryPelli** [discordcf/discordcf#41]
Is there a way to make them?

**Comment by alvgaona** [comment]
Yes, you can send embeds in the messages by just adding a list of embeds in the response to your command interaction. For instance, 

```typescript
return {
      type: InteractionResponseType.ChannelMessageWithSource,
      data: {
        content: `Hello, <@${userId}>`,
        embeds: [
          // Embed objects        
        ]
        allowed_mentions: {
          users: [userId || ''],
        },
      },
    };
```

To look at the structure of the embed objects, look at the Discord API reference: https://discord.com/developers/docs/resources/channel#embed-object

**Comment by alvgaona** [comment]
@LoryPelli also uses the "Issues" section to create feature requests or bugs. For Q&A, please, use our discussions section. Here's the link: https://github.com/discordcf/discordcf/discussions 😄

**Comment by LoryPelli** [comment]
> Yes, you can send embeds in the messages by just adding a list of embeds in the response to your command interaction. For instance,
> 
> ```ts
> return {
>       type: InteractionResponseType.ChannelMessageWithSource,
>       data: {
>         content: `Hello, <@${userId}>`,
>         embeds: [
>           // Embed objects        
>         ]
>         allowed_mentions: {
>           users: [userId || ''],
>         },
>       },
>     };
> ```
> 
> To look at the structure of the embed objects, look at the Discord API reference: https://discord.com/developers/docs/resources/channel#embed-object

How can I declare an embed?
I can't use
```js
let embed = new Discord.MessageEmbed()
```
So how?

**Comment by LoryPelli** [comment]
For future things I will use the discussion section

**Comment by alvgaona** [comment]
> > Yes, you can send embeds in the messages by just adding a list of embeds in the response to your command interaction. For instance,
> > ```ts
> > return {
> >       type: InteractionResponseType.ChannelMessageWithSource,
> >       data: {
> >         content: `Hello, <@${userId}>`,
> >         embeds: [
> >           // Embed objects        
> >         ]
> >         allowed_mentions: {
> >           users: [userId || ''],
> >         },
> >       },
> >     };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To look at the structure of the embed objects, look at the Discord API reference: https://discord.com/developers/docs/resources/channel#embed-object
> 
> How can I declare an embed? I can't use
> 
> ```js
> let embed = new Discord.MessageEmbed()
> ```
> 
> So how?

No, you just need to create a TypeScript object that has the fields the Discord API resource asks you to fill out.

```typescript
embeds: [
    {
        title: "something",
       type: "rich",
       ...
    }
]
```

Please make sure you read the link I shared above regarding the "Embed Object Structure".
