### ISSUE TITLE
JS Guide

### ISSUE THREAD

**Issue by LoryPelli** [discordcf/discordcf#42]
### Summary

A JS guide for this

### Intended Outcome

Will be useful

### How will it work?

The example TS code will be also in JS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvgaona** [comment]
@LoryPelli thanks for the input. I'm working on a documentation site for all of this.

**Comment by alvgaona** [comment]
@LoryPelli here's a starter repo with JavaScript that you can take a look at. I'll have this uploaded in the official site.
